GoogleCloudPlatform/covid-19-open-data

README.md
src/pipelines/epidemiology/config.yaml
src/pipelines/epidemiology/gb_authority.py
src/pipelines/epidemiology/gb_covid_19_uk_data.py

Only use this data from 01/04/2020 onward, the sources start to agree around then (but the match is not perfect).
UK data up to this point is from Tom White's aggregation.

Add L1/L2 authoritative UK data sources.

---

src/pipelines/epidemiology/config.yaml
src/pipelines/epidemiology/gb_authority.py
src/requirements.txt

Move other GB authority sources to use the new govt SDK.

Get L3 data for GB via SDK.

---

src/appengine.py
src/lib/data_source.py
src/lib/pipeline.py

Fixes #58
This also disambiguates the intermediate files for data sources which
are shared between multiple pipelines and have different schemas.

Improve performance of the combine step

---

src/appengine.py
src/lib/memory_efficient.py
src/pipelines/epidemiology/config.yaml
src/pipelines/hospitalizations/config.yaml
src/publish.py
src/test/test_memory_efficient.py

Simplify the latest subset group function to take latest known value per column

Simplify latest subset

---

src/appengine.py
src/lib/constants.py
src/requirements.txt
src/scripts/cloud_error_processing.py
src/scripts/schedule_jobs.py

Still need to add to cloud scheduler, will remove WIP once that's done.

Add script that will post new errors to github automatically

---

src/appengine.py

Fix empty return for route "report_errors_to_github".

---

src/pipelines/epidemiology/gb_authority.py
src/requirements.txt

See issue #95 for discussion of the fix.
Fixes #95.

Use new API query for death reported.

---

src/scripts/cloud_error_processing.py

Also link readable url to issue instead of API url.

Only report errors with count > 1.

---

src/Dockerfile
src/app.yaml
src/appengine.py
src/lib/constants.py
src/lib/gcloud.py
src/requirements.txt

Introduce a gcloud module to test using on-demand preemptible instances per job in place of AppEngine's manual scaling

gcloud preemptible instances

---

src/lib/data_source.py
src/lib/utils.py
src/pipelines/epidemiology/config.yaml
src/pipelines/epidemiology/gb_authority.py
src/test/test_table_utils.py

Enable the backfill flag for UK authoritative data.

Add a backfill option to config.

---

docs/table-search-trends.md

- Adding link to the new visualization for the dataset
- Updated the link to the anonymization doc to Arxiv.
- Minor text adjustments

Updating search trends documentation

---

src/appengine.py
src/lib/data_source.py
src/lib/error_logger.py
src/lib/pipeline.py
src/lib/wikidata.py
src/pipelines/epidemiology/es_cn_authority.py
src/pipelines/epidemiology/us_fl_authority.py
src/pipelines/epidemiology/xx_wikipedia.py
src/pipelines/hospitalizations/es_cn_authority.py
src/pipelines/worldbank/worldbank.py
src/publish.py
src/scripts/cloud_error_processing.py
src/test/test_source_run.py

This commit avoids modifying the root logger and instantiates a logger for each data source.

Improve logging functions

---

src/appengine.py
src/lib/error_logger.py
src/pipelines/epidemiology/config.yaml

* Enable parallel computation for udpate_table
* Use a single job for all epidemiology data sources
* Fix #229

Enable parallel computation for udpate_table

---

src/pipelines/epidemiology/config.yaml
src/pipelines/epidemiology/gb_authority.py

Let me know if we should only do one or the other.

Reinstate GB authority for L1 and remove Tom White data sources.

---

src/scripts/startup-script-setup.sh

Also fix minor issue with gunicorn config.

Add fluentd installation to the setup script.

---

docs/table-search-trends.md

Place IDs are now included in the dataset.

Update documentation to reflect dataset changes

---

examples/logistic_modeling.ipynb

Updated areas:
#df = pd.read_csv(f'https://storage.googleapis.com/covid19-open-data/v3/{data_key}/main.csv').set_index('date')
df = pd.read_csv(f'https://storage.googleapis.com/covid19-open-data/v3/location/{data_key}.csv').set_index('date')

Updating from V2 to V3 Schema

---

examples/data_loading.ipynb

Changes include: 
Moving from 'key' to 'location_key'...
Updating V2 to V3: "https://storage.googleapis.com/covid19-open-data/v3/latest/aggregated.csv"

Updating V2 to V3 Schema

---

README.md
docs/table-by-age.md
docs/table-by-sex.md
docs/table-demographics.md
docs/table-economy.md
docs/table-emergency-declarations.md
docs/table-epidemiology.md
docs/table-geography.md
docs/table-government-response.md
docs/table-health.md
docs/table-hospitalizations.md
docs/table-index.md
docs/table-mobility.md
docs/table-search-trends.md
docs/table-vaccinations.md
docs/table-weather.md
docs/table-worldbank.md
examples/data_loading.ipynb

Updating section on 'unique' data set justifications
Update README.md
Update table-by-age.md
update v2 to v3
Update table-by-sex.md
update v2 to v3
Update table-demographics.md
update v2 to v3
Update table-economy.md
update v2 to v3
Update table-emergency-declarations.md
update v2 to v3
Update table-epidemiology.md
update v2 to v3
Update table-geography.md
update v2 to v3
Update table-government-response.md
update v2 to v3
Update table-health.md
update v2 to v3
Update table-hospitalizations.md
update v2 to v3
Update table-index.md
update v2 to v3
Update table-mobility.md
update v2 to v3
Update table-search-trends.md
update v2 to v3
Update table-vaccinations.md
update v2 to v3
Update table-weather.md
update v2 to v3
Update table-worldbank.md
update v2 to v3
Update table-epidemiology.md …

Update docs to V3 schema

---

src/pipelines/demographics/config.yaml
src/pipelines/demographics/un_wpp.py
src/pipelines/worldbank/config.yaml
src/pipelines/worldbank/worldbank.py

Fix population density estimates
